language: node_js
node_js:  
  8
install:
  - npm install -g firebase-tools
  - npm install
script:
  npm run build
after_success:
  - firebase use --token $FIREBASE_TOKEN matthieu-f1348
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN