language: node_js
node_js:  
  8
cache:
  directories:
    - node_modules
install:
  - npm install -g firebase-tools
  - npm install --production
script:
  npm run build
after_success:
  - npm run deploy