export * from "./animals"
export * from "./css-showcase"
export * from "./fotos"
export * from "./home"
export * from "./home/parallax"
export * from "./not-found"
export * from "./des-trucs"
export * from "./clicks"
export * from "./highscores"
export * from "./dropfun"
export * from "./shadow"

